version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/odipweb/
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
   - location: script/after-install.sh
     timeout: 300
     runas: root
